# render.yaml

services:
  - type: web
    name: telegram-video-downloader-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
        value: # Render dashboard se manually add karein
